version: '3'

services:
    frontend:
      build: ./frontend
      image: frontend:latest
      environment:
        PORT: 3000
        PROXY_API: http://backend:8080/
      ports:
        - 3000:3000
    backend:
      build: ./backend
      image: backend:latest
      environment:
        - GEOCODIO_API_KEY=${GEOCODIO_API_KEY}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB} 
      ports:
        - 8080:8080
    database:
      build: ./database
      image: database:latest
      environment: 
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB} 
      ports:
        - 5432:5432
