version: '3'

services:
    frontend:
      build: ./frontend
      image: frontend:latest
      ports:
        - ${REACT_APP_PORT}:${REACT_APP_PORT}
    backend:
      build: ./backend
      image: backend:latest
      environment:
        - GEOCODIO_API_KEY=${GEOCODIO_API_KEY}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB} 
        - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
        - POSTGRES_PORT=${POSTGRES_PORT}
      ports:
        - ${KOTLIN_PORT}:${KOTLIN_PORT}
    database:
      build: ./database
      image: database:latest
      environment: 
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB} 
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
